sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "pypy"
  - "pypy3"
  # bleeding edge versions
  - "nightly"
install: true
matrix:
  fast_finish: true
  allow_failures:
  - python: "nightly"
install:
  - pip install .
script:
  - pytest
